---
apiVersion: "postgresql.cnpg.io/v1"
kind: "Cluster"
metadata:
  name: "romm-postgresql-cluster"
  namespace: "romm"
spec:
  instances: 2
  storage:
    size: "1Gi"
    storageClass: "longhorn"
  bootstrap:
    initdb:
      database: "romm"
      owner: "romm"
      secret:
        name: "romm-db-credentials"
